### ISSUE TITLE
Using emojis breaks layout or panics

### ISSUE THREAD

**Issue by nicoulaj** [zhiburt/tabled#9]
String length does not seem to be properly calculated when format strings contain emojis, leading to broken table layout or panic.

Sample code:
```rust
use tabled::{Tabled, table};

#[derive(Tabled)]
struct Language {
    name: &'static str,
    designed_by: &'static str,
    invented_year: usize,
}

fn main() {
    let languages = vec![
        Language {
            name: "C",
            designed_by: "Dennis Ritchie 💕",
            invented_year: 1972
        },
        Language {
            name: "Rust 👍",
            designed_by: "Graydon Hoare",
            invented_year: 2010
        },
        Language {
            name: "Go 🤢",
            designed_by: "Rob Pike",
            invented_year: 2009
        },
    ];

    print!("{}", table!(&languages));
}
```

Crashes with:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /home/nicoulaj/.cargo/registry/src/github.com-1ecc6299db9ec823/papergrid-0.1.9/src/lib.rs:343:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:69:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /home/nicoulaj/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:182:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /home/nicoulaj/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /home/nicoulaj/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2381:9
   6: papergrid::Grid::build_row
             at /home/nicoulaj/.cargo/registry/src/github.com-1ecc6299db9ec823/papergrid-0.1.9/src/lib.rs:343:33
   7: <papergrid::Grid as core::fmt::Display>::fmt
             at /home/nicoulaj/.cargo/registry/src/github.com-1ecc6299db9ec823/papergrid-0.1.9/src/lib.rs:599:13
   8: <&T as core::fmt::Display>::fmt
             at /home/nicoulaj/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2010:62
   9: core::fmt::write
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
  10: core::fmt::Write::write_fmt
             at /home/nicoulaj/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:182:9
  11: <T as alloc::string::ToString>::to_string
             at /home/nicoulaj/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:2270:9
```

**Comment by zhiburt** [comment]
It supposed to be fixed @nicoulaj please check a master branch.

Thanks a lot for reporting this issue.

**Comment by nicoulaj** [comment]
Looks good to me, thanks!
